version: 2

sources:
  - name: raw
    description: "Raw Telegram data"
    tables:
      - name: telegram_messages
      - name: yolo_detections
        description: "YOLO object detection results on Telegram images"